// قائمة جميع دول العالم بالعربية مع رمز الهاتف
const countriesAr = [
  { nameAr: "أفغانستان", nameEn: "Afghanistan", code: "AF", phone: "+93" },
  { nameAr: "ألبانيا", nameEn: "Albania", code: "AL", phone: "+355" },
  { nameAr: "الجزائر", nameEn: "Algeria", code: "DZ", phone: "+213" },
  { nameAr: "أندورا", nameEn: "Andorra", code: "AD", phone: "+376" },
  { nameAr: "أنغولا", nameEn: "Angola", code: "AO", phone: "+244" },
  {
    nameAr: "أنتيغوا وباربودا",
    nameEn: "Antigua and Barbuda",
    code: "AG",
    phone: "+1-268",
  },
  { nameAr: "الأرجنتين", nameEn: "Argentina", code: "AR", phone: "+54" },
  { nameAr: "أرمينيا", nameEn: "Armenia", code: "AM", phone: "+374" },
  { nameAr: "أستراليا", nameEn: "Australia", code: "AU", phone: "+61" },
  { nameAr: "النمسا", nameEn: "Austria", code: "AT", phone: "+43" },
  { nameAr: "أذربيجان", nameEn: "Azerbaijan", code: "AZ", phone: "+994" },
  { nameAr: "الباهاما", nameEn: "Bahamas", code: "BS", phone: "+1-242" },
  { nameAr: "البحرين", nameEn: "Bahrain", code: "BH", phone: "+973" },
  { nameAr: "بنغلاديش", nameEn: "Bangladesh", code: "BD", phone: "+880" },
  { nameAr: "باربادوس", nameEn: "Barbados", code: "BB", phone: "+1-246" },
  { nameAr: "بيلاروسيا", nameEn: "Belarus", code: "BY", phone: "+375" },
  { nameAr: "بلجيكا", nameEn: "Belgium", code: "BE", phone: "+32" },
  { nameAr: "بليز", nameEn: "Belize", code: "BZ", phone: "+501" },
  { nameAr: "بنين", nameEn: "Benin", code: "BJ", phone: "+229" },
  { nameAr: "بوتان", nameEn: "Bhutan", code: "BT", phone: "+975" },
  { nameAr: "بوليفيا", nameEn: "Bolivia", code: "BO", phone: "+591" },
  {
    nameAr: "البوسنة والهرسك",
    nameEn: "Bosnia and Herzegovina",
    code: "BA",
    phone: "+387",
  },
  { nameAr: "بوتسوانا", nameEn: "Botswana", code: "BW", phone: "+267" },
  { nameAr: "البرازيل", nameEn: "Brazil", code: "BR", phone: "+55" },
  { nameAr: "بروناي", nameEn: "Brunei", code: "BN", phone: "+673" },
  { nameAr: "بلغاريا", nameEn: "Bulgaria", code: "BG", phone: "+359" },
  { nameAr: "بوركينا فاسو", nameEn: "Burkina Faso", code: "BF", phone: "+226" },
  { nameAr: "بوروندي", nameEn: "Burundi", code: "BI", phone: "+257" },
  { nameAr: "كمبوديا", nameEn: "Cambodia", code: "KH", phone: "+855" },
  { nameAr: "الكاميرون", nameEn: "Cameroon", code: "CM", phone: "+237" },
  { nameAr: "كندا", nameEn: "Canada", code: "CA", phone: "+1" },
  { nameAr: "الرأس الأخضر", nameEn: "Cape Verde", code: "CV", phone: "+238" },
  {
    nameAr: "جمهورية أفريقيا الوسطى",
    nameEn: "Central African Republic",
    code: "CF",
    phone: "+236",
  },
  { nameAr: "تشاد", nameEn: "Chad", code: "TD", phone: "+235" },
  { nameAr: "تشيلي", nameEn: "Chile", code: "CL", phone: "+56" },
  { nameAr: "الصين", nameEn: "China", code: "CN", phone: "+86" },
  { nameAr: "كولومبيا", nameEn: "Colombia", code: "CO", phone: "+57" },
  { nameAr: "جزر القمر", nameEn: "Comoros", code: "KM", phone: "+269" },
  { nameAr: "الكونغو", nameEn: "Congo", code: "CG", phone: "+242" },
  {
    nameAr: "جمهورية الكونغو الديمقراطية",
    nameEn: "Democratic Republic of the Congo",
    code: "CD",
    phone: "+243",
  },
  { nameAr: "كوستاريكا", nameEn: "Costa Rica", code: "CR", phone: "+506" },
  { nameAr: "ساحل العاج", nameEn: "Ivory Coast", code: "CI", phone: "+225" },
  { nameAr: "كرواتيا", nameEn: "Croatia", code: "HR", phone: "+385" },
  { nameAr: "كوبا", nameEn: "Cuba", code: "CU", phone: "+53" },
  { nameAr: "قبرص", nameEn: "Cyprus", code: "CY", phone: "+357" },
  { nameAr: "التشيك", nameEn: "Czech Republic", code: "CZ", phone: "+420" },
  { nameAr: "الدنمارك", nameEn: "Denmark", code: "DK", phone: "+45" },
  { nameAr: "جيبوتي", nameEn: "Djibouti", code: "DJ", phone: "+253" },
  { nameAr: "دومينيكا", nameEn: "Dominica", code: "DM", phone: "+1-767" },
  {
    nameAr: "جمهورية الدومينيكان",
    nameEn: "Dominican Republic",
    code: "DO",
    phone: "+1-809",
  },
  { nameAr: "تيمور الشرقية", nameEn: "East Timor", code: "TL", phone: "+670" },
  { nameAr: "الإكوادور", nameEn: "Ecuador", code: "EC", phone: "+593" },
  { nameAr: "مصر", nameEn: "Egypt", code: "EG", phone: "+20" },
  { nameAr: "السلفادور", nameEn: "El Salvador", code: "SV", phone: "+503" },
  {
    nameAr: "غينيا الاستوائية",
    nameEn: "Equatorial Guinea",
    code: "GQ",
    phone: "+240",
  },
  { nameAr: "إريتريا", nameEn: "Eritrea", code: "ER", phone: "+291" },
  { nameAr: "إستونيا", nameEn: "Estonia", code: "EE", phone: "+372" },
  { nameAr: "إسواتيني", nameEn: "Eswatini", code: "SZ", phone: "+268" },
  { nameAr: "إثيوبيا", nameEn: "Ethiopia", code: "ET", phone: "+251" },
  { nameAr: "فيجي", nameEn: "Fiji", code: "FJ", phone: "+679" },
  { nameAr: "فنلندا", nameEn: "Finland", code: "FI", phone: "+358" },
  { nameAr: "فرنسا", nameEn: "France", code: "FR", phone: "+33" },
  { nameAr: "الغابون", nameEn: "Gabon", code: "GA", phone: "+241" },
  { nameAr: "غامبيا", nameEn: "Gambia", code: "GM", phone: "+220" },
  { nameAr: "جورجيا", nameEn: "Georgia", code: "GE", phone: "+995" },
  { nameAr: "ألمانيا", nameEn: "Germany", code: "DE", phone: "+49" },
  { nameAr: "غانا", nameEn: "Ghana", code: "GH", phone: "+233" },
  { nameAr: "اليونان", nameEn: "Greece", code: "GR", phone: "+30" },
  { nameAr: "غرينادا", nameEn: "Grenada", code: "GD", phone: "+1-473" },
  { nameAr: "غواتيمالا", nameEn: "Guatemala", code: "GT", phone: "+502" },
  { nameAr: "غينيا", nameEn: "Guinea", code: "GN", phone: "+224" },
  { nameAr: "غينيا بيساو", nameEn: "Guinea-Bissau", code: "GW", phone: "+245" },
  { nameAr: "غيانا", nameEn: "Guyana", code: "GY", phone: "+592" },
  { nameAr: "هايتي", nameEn: "Haiti", code: "HT", phone: "+509" },
  { nameAr: "هندوراس", nameEn: "Honduras", code: "HN", phone: "+504" },
  { nameAr: "المجر", nameEn: "Hungary", code: "HU", phone: "+36" },
  { nameAr: "آيسلندا", nameEn: "Iceland", code: "IS", phone: "+354" },
  { nameAr: "الهند", nameEn: "India", code: "IN", phone: "+91" },
  { nameAr: "إندونيسيا", nameEn: "Indonesia", code: "ID", phone: "+62" },
  { nameAr: "إيران", nameEn: "Iran", code: "IR", phone: "+98" },
  { nameAr: "العراق", nameEn: "Iraq", code: "IQ", phone: "+964" },
  { nameAr: "أيرلندا", nameEn: "Ireland", code: "IE", phone: "+353" },
  { nameAr: "إسرائيل", nameEn: "Israel", code: "IL", phone: "+972" },
  { nameAr: "إيطاليا", nameEn: "Italy", code: "IT", phone: "+39" },
  { nameAr: "جامايكا", nameEn: "Jamaica", code: "JM", phone: "+1-876" },
  { nameAr: "اليابان", nameEn: "Japan", code: "JP", phone: "+81" },
  { nameAr: "الأردن", nameEn: "Jordan", code: "JO", phone: "+962" },
  { nameAr: "كازاخستان", nameEn: "Kazakhstan", code: "KZ", phone: "+7" },
  { nameAr: "كينيا", nameEn: "Kenya", code: "KE", phone: "+254" },
  { nameAr: "كيريباتي", nameEn: "Kiribati", code: "KI", phone: "+686" },
  {
    nameAr: "كوريا الشمالية",
    nameEn: "North Korea",
    code: "KP",
    phone: "+850",
  },
  { nameAr: "كوريا الجنوبية", nameEn: "South Korea", code: "KR", phone: "+82" },
  { nameAr: "الكويت", nameEn: "Kuwait", code: "KW", phone: "+965" },
  { nameAr: "قيرغيزستان", nameEn: "Kyrgyzstan", code: "KG", phone: "+996" },
  { nameAr: "لاوس", nameEn: "Laos", code: "LA", phone: "+856" },
  { nameAr: "لاتفيا", nameEn: "Latvia", code: "LV", phone: "+371" },
  { nameAr: "لبنان", nameEn: "Lebanon", code: "LB", phone: "+961" },
  { nameAr: "ليسوتو", nameEn: "Lesotho", code: "LS", phone: "+266" },
  { nameAr: "ليبيريا", nameEn: "Liberia", code: "LR", phone: "+231" },
  { nameAr: "ليبيا", nameEn: "Libya", code: "LY", phone: "+218" },
  { nameAr: "ليختنشتاين", nameEn: "Liechtenstein", code: "LI", phone: "+423" },
  { nameAr: "ليتوانيا", nameEn: "Lithuania", code: "LT", phone: "+370" },
  { nameAr: "لوكسمبورغ", nameEn: "Luxembourg", code: "LU", phone: "+352" },
  { nameAr: "مدغشقر", nameEn: "Madagascar", code: "MG", phone: "+261" },
  { nameAr: "مالاوي", nameEn: "Malawi", code: "MW", phone: "+265" },
  { nameAr: "ماليزيا", nameEn: "Malaysia", code: "MY", phone: "+60" },
  { nameAr: "جزر المالديف", nameEn: "Maldives", code: "MV", phone: "+960" },
  { nameAr: "مالي", nameEn: "Mali", code: "ML", phone: "+223" },
  { nameAr: "مالطا", nameEn: "Malta", code: "MT", phone: "+356" },
  {
    nameAr: "جزر مارشال",
    nameEn: "Marshall Islands",
    code: "MH",
    phone: "+692",
  },
  { nameAr: "موريتانيا", nameEn: "Mauritania", code: "MR", phone: "+222" },
  { nameAr: "موريشيوس", nameEn: "Mauritius", code: "MU", phone: "+230" },
  { nameAr: "المكسيك", nameEn: "Mexico", code: "MX", phone: "+52" },
  {
    nameAr: "ولايات ميكرونيسيا المتحدة",
    nameEn: "Micronesia",
    code: "FM",
    phone: "+691",
  },
  { nameAr: "مولدوفا", nameEn: "Moldova", code: "MD", phone: "+373" },
  { nameAr: "موناكو", nameEn: "Monaco", code: "MC", phone: "+377" },
  { nameAr: "منغوليا", nameEn: "Mongolia", code: "MN", phone: "+976" },
  { nameAr: "الجبل الأسود", nameEn: "Montenegro", code: "ME", phone: "+382" },
  { nameAr: "المغرب", nameEn: "Morocco", code: "MA", phone: "+212" },
  { nameAr: "موزمبيق", nameEn: "Mozambique", code: "MZ", phone: "+258" },
  { nameAr: "ميانمار", nameEn: "Myanmar", code: "MM", phone: "+95" },
  { nameAr: "ناميبيا", nameEn: "Namibia", code: "NA", phone: "+264" },
  { nameAr: "ناورو", nameEn: "Nauru", code: "NR", phone: "+674" },
  { nameAr: "نيبال", nameEn: "Nepal", code: "NP", phone: "+977" },
  { nameAr: "هولندا", nameEn: "Netherlands", code: "NL", phone: "+31" },
  { nameAr: "نيوزيلندا", nameEn: "New Zealand", code: "NZ", phone: "+64" },
  { nameAr: "نيكاراغوا", nameEn: "Nicaragua", code: "NI", phone: "+505" },
  { nameAr: "النيجر", nameEn: "Niger", code: "NE", phone: "+227" },
  { nameAr: "نيجيريا", nameEn: "Nigeria", code: "NG", phone: "+234" },
  {
    nameAr: "مقدونيا الشمالية",
    nameEn: "North Macedonia",
    code: "MK",
    phone: "+389",
  },
  { nameAr: "النرويج", nameEn: "Norway", code: "NO", phone: "+47" },
  { nameAr: "عمان", nameEn: "Oman", code: "OM", phone: "+968" },
  { nameAr: "باكستان", nameEn: "Pakistan", code: "PK", phone: "+92" },
  { nameAr: "بالاو", nameEn: "Palau", code: "PW", phone: "+680" },
  { nameAr: "فلسطين", nameEn: "Palestine", code: "PS", phone: "+970" },
  { nameAr: "بنما", nameEn: "Panama", code: "PA", phone: "+507" },
  {
    nameAr: "بابوا غينيا الجديدة",
    nameEn: "Papua New Guinea",
    code: "PG",
    phone: "+675",
  },
  { nameAr: "باراغواي", nameEn: "Paraguay", code: "PY", phone: "+595" },
  { nameAr: "بيرو", nameEn: "Peru", code: "PE", phone: "+51" },
  { nameAr: "الفلبين", nameEn: "Philippines", code: "PH", phone: "+63" },
  { nameAr: "بولندا", nameEn: "Poland", code: "PL", phone: "+48" },
  { nameAr: "البرتغال", nameEn: "Portugal", code: "PT", phone: "+351" },
  { nameAr: "قطر", nameEn: "Qatar", code: "QA", phone: "+974" },
  { nameAr: "رومانيا", nameEn: "Romania", code: "RO", phone: "+40" },
  { nameAr: "روسيا", nameEn: "Russia", code: "RU", phone: "+7" },
  { nameAr: "رواندا", nameEn: "Rwanda", code: "RW", phone: "+250" },
  {
    nameAr: "سانت كيتس ونيفيس",
    nameEn: "Saint Kitts and Nevis",
    code: "KN",
    phone: "+1-869",
  },
  { nameAr: "سانت لوسيا", nameEn: "Saint Lucia", code: "LC", phone: "+1-758" },
  {
    nameAr: "سانت فنسنت والغرينادين",
    nameEn: "Saint Vincent and the Grenadines",
    code: "VC",
    phone: "+1-784",
  },
  { nameAr: "ساموا", nameEn: "Samoa", code: "WS", phone: "+685" },
  { nameAr: "سان مارينو", nameEn: "San Marino", code: "SM", phone: "+378" },
  {
    nameAr: "ساو تومي وبرينسيب",
    nameEn: "Sao Tome and Principe",
    code: "ST",
    phone: "+239",
  },
  { nameAr: "السعودية", nameEn: "Saudi Arabia", code: "SA", phone: "+966" },
  { nameAr: "السنغال", nameEn: "Senegal", code: "SN", phone: "+221" },
  { nameAr: "صربيا", nameEn: "Serbia", code: "RS", phone: "+381" },
  { nameAr: "سيشيل", nameEn: "Seychelles", code: "SC", phone: "+248" },
  { nameAr: "سيراليون", nameEn: "Sierra Leone", code: "SL", phone: "+232" },
  { nameAr: "سنغافورة", nameEn: "Singapore", code: "SG", phone: "+65" },
  { nameAr: "سلوفاكيا", nameEn: "Slovakia", code: "SK", phone: "+421" },
  { nameAr: "سلوفينيا", nameEn: "Slovenia", code: "SI", phone: "+386" },
  {
    nameAr: "جزر سليمان",
    nameEn: "Solomon Islands",
    code: "SB",
    phone: "+677",
  },
  { nameAr: "الصومال", nameEn: "Somalia", code: "SO", phone: "+252" },
  { nameAr: "جنوب أفريقيا", nameEn: "South Africa", code: "ZA", phone: "+27" },
  {
    nameAr: "كوريا الجنوبية",
    nameEn: "South Korea",
    code: "KR&",
    phone: "+82",
  },
  { nameAr: "جنوب السودان", nameEn: "South Sudan", code: "SS", phone: "+211" },
  { nameAr: "إسبانيا", nameEn: "Spain", code: "ES", phone: "+34" },
  { nameAr: "سريلانكا", nameEn: "Sri Lanka", code: "LK", phone: "+94" },
  { nameAr: "السودان", nameEn: "Sudan", code: "SD", phone: "+249" },
  { nameAr: "سورينام", nameEn: "Suriname", code: "SR", phone: "+597" },
  { nameAr: "السويد", nameEn: "Sweden", code: "SE", phone: "+46" },
  { nameAr: "سويسرا", nameEn: "Switzerland", code: "CH", phone: "+41" },
  { nameAr: "سوريا", nameEn: "Syria", code: "SY", phone: "+963" },
  { nameAr: "تايوان", nameEn: "Taiwan", code: "TW", phone: "+886" },
  { nameAr: "طاجيكستان", nameEn: "Tajikistan", code: "TJ", phone: "+992" },
  { nameAr: "تنزانيا", nameEn: "Tanzania", code: "TZ", phone: "+255" },
  { nameAr: "تايلاند", nameEn: "Thailand", code: "TH", phone: "+66" },
  { nameAr: "توغو", nameEn: "Togo", code: "TG", phone: "+228" },
  { nameAr: "تونغا", nameEn: "Tonga", code: "TO", phone: "+676" },
  {
    nameAr: "ترينيداد وتوباغو",
    nameEn: "Trinidad and Tobago",
    code: "TT",
    phone: "+1-868",
  },
  { nameAr: "تونس", nameEn: "Tunisia", code: "TN", phone: "+216" },
  { nameAr: "تركيا", nameEn: "Turkey", code: "TR", phone: "+90" },
  { nameAr: "تركمانستان", nameEn: "Turkmenistan", code: "TM", phone: "+993" },
  { nameAr: "توفالو", nameEn: "Tuvalu", code: "TV", phone: "+688" },
  { nameAr: "أوغندا", nameEn: "Uganda", code: "UG", phone: "+256" },
  { nameAr: "أوكرانيا", nameEn: "Ukraine", code: "UA", phone: "+380" },
  {
    nameAr: "الإمارات العربية المتحدة",
    nameEn: "United Arab Emirates",
    code: "AE",
    phone: "+971",
  },
  {
    nameAr: "المملكة المتحدة",
    nameEn: "United Kingdom",
    code: "GB",
    phone: "+44",
  },
  {
    nameAr: "الولايات المتحدة",
    nameEn: "United States",
    code: "US",
    phone: "+1",
  },
  { nameAr: "أوروغواي", nameEn: "Uruguay", code: "UY", phone: "+598" },
  { nameAr: "أوزبكستان", nameEn: "Uzbekistan", code: "UZ", phone: "+998" },
  { nameAr: "فانواتو", nameEn: "Vanuatu", code: "VU", phone: "+678" },
  { nameAr: "فنزويلا", nameEn: "Venezuela", code: "VE", phone: "+58" },
  { nameAr: "فيتنام", nameEn: "Vietnam", code: "VN", phone: "+84" },
  { nameAr: "اليمن", nameEn: "Yemen", code: "YE", phone: "+967" },
  { nameAr: "زامبيا", nameEn: "Zambia", code: "ZM", phone: "+260" },
  { nameAr: "زيمبابوي", nameEn: "Zimbabwe", code: "ZW", phone: "+263" },
];

export default countriesAr;
